#!/bin/bash

echo Initializing custom setup ...

# Install packages
sudo apt-get update
sudo apt-get install -y git tmux alacritty fzf ripgrep

# Compile nvim
if command -v nvim > /dev/null 2>&1; then
    echo Neovim has already been installed!
else
    echo Attempting to compile nvim from source ...
    nvim_repo=/tmp/neovim-repo
    git clone --depth=1 --branch=nightly \
        https://github.com/neovim/neovim $nvim_repo
    cd $nvim_repo
    sudo apt-get install -y cmake
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    sudo make install
    cd - > /dev/null
    rm -rf $nvim_repo
    nvim --version
fi

# .bashrc additions
config_line=". ~/bin/.bashrc"
config_segment="
# PERSONAL ADDITIONS
$config_line
"
if [[ -z "$(cat ~/.bashrc | grep "$config_line")" ]]
    then
        echo "$config_segment" >> ~/.bashrc
        echo Config added to .bashrc!
    else
        echo Config in .bashrc had already been set up!
fi

# .vimrc additions
config_line="source ~/bin/.vimrc"
config_segment="
\" PERSONAL ADDITIONS
$config_line
"
touch ~/.vimrc
if [[ -z "$(cat ~/.vimrc | grep "$config_line")" ]]
    then
        echo "$config_segment" >> ~/.vimrc
        echo Config added to .vimrc!
    else
        echo Config in .vimrc had already been set up!
fi

# .tmux.conf additions
config_line="source-file ~/bin/tmux/.tmux.conf"
config_segment="
# PERSONAL ADDITIONS
$config_line
"
touch ~/.tmux.conf
if [[ -z "$(cat ~/.tmux.conf | grep "$config_line")" ]]
    then
        echo "$config_segment" >> ~/.tmux.conf
        echo Config added to .tmux.conf!
    else
        echo Config in .tmux.conf had already been set up!
fi

# alacritty config
my_config=~/bin/alacritty/alacritty.toml
local_config=~/.config/alacritty/alacritty.toml
additional_config=~/.config/alacritty/alacritty_additional.toml
if diff --new-file "$local_config" "$my_config" > /dev/null; then
    # Local config and config in bin/ are the same
    echo Config for alacritty had already been set up!
else
    mkdir --parents ~/.config/alacritty
    cp --backup=numbered "$my_config" "$local_config"
    touch "$additional_config"
    echo Config for alacritty set up!
fi

# nvim config
my_config=~/bin/nvim/init.lua
local_config=~/.config/nvim/init.lua
additional_config_dir=~/.config/nvim/lua/config_additional/
additional_config=$additional_config_dir/init.lua
if diff --new-file "$local_config" "$my_config" > /dev/null; then
    # Local config and config in bin/ are the same
    echo Config for nvim had already been set up!
else
    mkdir --parents "$additional_config_dir"
    cp --backup=numbered "$my_config" "$local_config"
    touch "$additional_config"
    echo Config for nvim set up!
fi

# git config
git config --global core.excludesfile ~/bin/.gitignore_global
git config --global core.editor nvim
git config --global init.defaultbranch main
git config --global advice.detachedhead false
git config --global diff.tool nvimdiff
git config --global difftool.prompt false
git config --global alias.df "difftool"
git config --global alias.adog "log --all --decorate --oneline --graph"
echo "Config for git (global) set up!"

echo Setup complete!

