if [[ ! -v _TODOEXITCODES_SOURCED ]]; then
    _TODOEXITCODES_SOURCED=true
    readonly TODOEXITCODES_SUCCESS=0
    readonly TODOEXITCODES_INVALID_USAGE=2
    readonly TODOEXITCODES_INVALID_NAME=65
    readonly TODOEXITCODES_DOES_NOT_EXIST=66
    readonly TODOEXITCODES_ALREADY_EXISTS=73
fi

