[[ -v _TODOLIB_EXITS__SOURCED ]] && return
readonly _TODOLIB_EXITS__SOURCED=true

readonly _TODOLIB_EXITS_SUCCESS=0
readonly _TODOLIB_EXITS_INVALID_USAGE=2
readonly _TODOLIB_EXITS_INVALID_NAME=65
readonly _TODOLIB_EXITS_DOES_NOT_EXIST=66
readonly _TODOLIB_EXITS_ALREADY_EXISTS=73
